### ISSUE TITLE
Tips for starting a Repair Café

### ISSUE THREAD

**Issue by dawaedina27** [Math-TECH-Hub/CommunityRepairCafe#10]
### Few Tips for starting a Repair Cafe

1.**Visit a couple of established Repair Cafes**

2. **Don’t get hung up on health and safety and insurance.** 
           > Make sure repairers work within the limits of their skills and, if necessary, get help from 
               other repairers. 
           > Explain to owners that you are enthusiastic amateurs not paid professionals (also use a 
              disclaimer
          > Don’t take on a major repair if you’re not happy to do so for any reason. We always say we’re a clinic not a hospital. 
        
3. **Get advance bookings**

4.**Try to make sure your venue allows you to have repairs and waiting area in the same space.** This means waiting owners can see what’s going on – that there’s a queue – and don’t feel they are being ignored.

5. **Encourage repairers to give a running commentary** Owners are expected to stay with their items and the repairers while s/he assesses the problem and talks through any repairs undertaken. 
The idea is that the owner leaves knowing more about his/her item than when they arrived. Some Repair Cafes offer ‘skillshare’ sessions to teach DIY repair work.

6. **Encourage repairers to be honest about their abilities.**

7. **Get owners to sign a ‘disclaimer’ when they arrive.** A Repair Cafe should have a set of ‘rules’ that clarifies the relationship between owner and repairer. Ask the owners to read and sign it – it will not stand up in court but helps establish the amateur nature of our (voluntary) work.

8. **Do some market research**. You can test out the best times and days for running your events.

9. **Get feedback** We ask attenders to filling in a short series of questions when they leave and also record the success (or otherwise) of assessment and repair. This is useful for publicity, for reporting back to repairers, and useful if you ever need to make a grant application for running costs.

10. **Invite donations** We alert people in advance to the fact that the event is free, but we appreciate donations to cover insurance, venue hire, refreshments, consumables such as glues and fuses, publicity materials etc

**Comment by chardso** [comment]
Devices DAT requir

**Comment by chardso** [comment]
Spares are bought by the owners,and we offer free labour.

**Comment by timmwille** [comment]
@dawaedina27 I just see this now, amazing can you add this as an issue in the group repository so we can collaborate on it?
https://github.com/ASKnet-Open-Training/CommunityRepairCafe/issues

if done/posted there, we can link it here and close this issue

**Comment by timmwille** [comment]
also add the comments @chardso commented here!

**Comment by timmwille** [comment]
@dawaedina27 @Math-TECH-Hub looks a bit like the nice info in here is not yet included in here or in the repo? am I wrong?
https://github.com/ASKnet-Open-Training/CommunityRepairCafe/issues/2
