### ISSUE TITLE
First Aid Kit

### ISSUE THREAD

**Issue by Math-TECH-Hub** [Math-TECH-Hub/CommunityRepairCafe#12]
What are the necessary basic things(medicine & materials)to include in a first aid kit for a repair cafe?
Let's contribute please.

**Comment by chardso** [comment]
- hydrogen peroxide
- panadol
-  Bandage
-  Cotton wool
-  Apair of scisor.

**Comment by timmwille** [comment]
- disinfectant
- Ointment gel
- band-aid/patches
