### ISSUE TITLE
There misusage of the read me file

### ISSUE THREAD

**Issue by PyGamma** [Math-TECH-Hub/CommunityRepairCafe#5]
Hey team, this is really great work  however, I recommend that the read me file should be used for describing the repository only not for scripting the entire content of the project or activities idea. So please create a file and move most of the details you have provided here and leave only the description of the repository in the read me file. Doing this as soon as possible will give us the opportunity to move forward.

**Comment by timmwille** [comment]
good point let's fix it over here:
https://github.com/ASKnet-Open-Training/CommunityRepairCafe

I'll created a similar Issue there https://github.com/ASKnet-Open-Training/CommunityRepairCafe/issues/5

**Comment by Math-TECH-Hub** [comment]
How can I remove move?
